### ISSUE TITLE
Dose library support constraint exclusion query ?

### ISSUE THREAD

**Issue by azadious** [chaitin/django-pg-partitioning#8]
From postgres document https://www.postgresql.org/docs/current/ddl-partitioning.html#DDL-PARTITION-PRUNING. If this library support constraint exclusion we can query in master model and planner will choose the suitable child, every query will faster and code simple.

**Comment by virusdefender** [comment]
I think it's enabled by default if you `SET enable_partition_pruning = on`.

In most cases, you should use the master table name to make queries.

**Comment by azadious** [comment]
Great, thank you very much your library is very useful.
